'use strict';

/**
 * Database Visualizer/Health Server
 *
 * This script is designed to be safe to execute in environments where Node.js dependencies
 * (like express and database drivers) may not be installed. By default, it runs in "lite" mode
 * which exposes a minimal health/info endpoint using Node's built-in http module.
 *
 * To enable the full Express-powered viewer, install dependencies and set:
 *   DB_VISUALIZER_ENABLED=1
 * Then start:
 *   node server.js --host 0.0.0.0 --port 3070
 *
 * Optional: Source environment variables generated by the PostgreSQL startup script:
 *   source postgres.env
 */

// Built-in modules only at top-level to avoid external module errors
const http = require('http');
const path = require('path');
const fs = require('fs');

// Utility: Safe require that returns null when module is missing
function safeRequire(modName) {
  try {
    return require(modName);
  } catch (_err) {
    return null;
  }
}

// Parse CLI args
function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i];
    if (k === '--host' && argv[i + 1]) {
      args.host = argv[++i];
    } else if (k === '--port' && argv[i + 1]) {
      const p = parseInt(argv[++i], 10);
      if (!Number.isNaN(p)) args.port = p;
    } else if (k === '--enable' || k === '--full') {
      args.enable = true;
    } else if (k === '--lite') {
      args.lite = true;
    }
  }
  return args;
}

function isTruthy(val) {
  if (val === true) return true;
  if (typeof val !== 'string') return false;
  const v = val.trim().toLowerCase();
  return v === '1' || v === 'true' || v === 'yes' || v === 'on';
}

/**
 * Load env vars from local .env-like files (postgres.env, mysql.env, sqlite.env, mongodb.env).
 * These files are optional; present only if created by startup scripts.
 */
function loadEnvFiles() {
  const envFiles = ['postgres', 'mysql', 'sqlite', 'mongodb'];
  const allEnvVars = {};

  envFiles.forEach((dbType) => {
    const filePath = `${dbType}.env`;
    if (!fs.existsSync(filePath)) return;

    try {
      const content = fs.readFileSync(filePath, 'utf8');
      let varsLoaded = 0;

      content.split('\n').forEach((line) => {
        const trimmed = line.trim();
        if (trimmed && trimmed.startsWith('export ')) {
          const exportLine = trimmed.substring(7);
          const [key, ...valueParts] = exportLine.split('=');
          if (key && valueParts.length > 0) {
            let value = valueParts.join('=');
            if (
              (value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))
            ) {
              value = value.slice(1, -1);
            }
            allEnvVars[key] = value;
            varsLoaded++;
          }
        }
      });

      console.log(`✓ ${filePath} loaded (${varsLoaded} variables)`);
    } catch (error) {
      console.log(`✗ Error loading ${filePath}:`, error.message);
    }
  });

  return { ...process.env, ...allEnvVars };
}

const args = parseArgs(process.argv.slice(2));
const mergedEnv = loadEnvFiles();

const ENABLE_FULL =
  args.enable || (!args.lite && isTruthy(process.env.DB_VISUALIZER_ENABLED));
const HOST = args.host || process.env.HOST || '0.0.0.0';
const PORT = args.port || parseInt(process.env.VISUALIZER_PORT || process.env.PORT || '3070', 10);

/**
 * Create and start a minimal HTTP server that provides health information and
 * guidance on enabling the full viewer. This server uses no external dependencies.
 *
 * PUBLIC_INTERFACE
 * @param {number} port - Port to listen on
 * @param {string} host - Host to bind
 * @returns {http.Server} - The created server instance
 */
function createLiteServer(port, host) {
  const server = http.createServer((req, res) => {
    const payload = {
      status: 'ok',
      mode: 'lite',
      message:
        'Database viewer is disabled or Node dependencies are not installed. PostgreSQL remains available.',
      enable_instructions:
        'To enable full viewer: cd db_visualizer && npm ci && DB_VISUALIZER_ENABLED=1 node server.js --host 0.0.0.0 --port 3070',
      env_file_hint:
        'If using PostgreSQL with the startup script, run: source db_visualizer/postgres.env',
      docs: {
        endpoints: {
          health: '/',
        },
      },
      timestamp: new Date().toISOString(),
    };

    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.end(JSON.stringify(payload, null, 2));
  });

  server.listen(port, host, () => {
    console.log(`Lite database server running on http://${host}:${port}`);
    if (!ENABLE_FULL) {
      console.log('Full viewer disabled. Set DB_VISUALIZER_ENABLED=1 to enable.');
    }
  });

  return server;
}

/**
 * Start the full Express-powered database viewer if express is available.
 * If any required module is missing, this function returns null so the caller can fallback.
 *
 * PUBLIC_INTERFACE
 * @param {number} port - Port to listen on
 * @param {string} host - Host to bind
 * @param {Record<string, string>} envVars - Environment variables to use for DB configs
 * @returns {import('http').Server|null} - HTTP server instance or null if express not available
 */
function startExpressApp(port, host, envVars) {
  const express = safeRequire('express');
  if (!express) {
    console.log('express module not found. Falling back to lite server without Express.');
    return null;
  }

  // Optional drivers; adapters will error gracefully if missing
  const pgModule = safeRequire('pg');
  const Pool = pgModule ? pgModule.Pool : null;
  const mysql = safeRequire('mysql2/promise');
  const sqlite3Base = safeRequire('sqlite3');
  const sqlite3 = sqlite3Base ? sqlite3Base.verbose() : null;
  const mongodbModule = safeRequire('mongodb');
  const MongoClient = mongodbModule ? mongodbModule.MongoClient : null;

  const app = express();

  // Security/CORS headers to allow iframe embedding and API calls
  app.use((req, res, next) => {
    res.setHeader('X-Frame-Options', 'ALLOWALL');
    res.setHeader('Content-Security-Policy', 'frame-ancestors *;');
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,PATCH,OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type,Authorization');
    if (req.method === 'OPTIONS') {
      return res.sendStatus(204);
    }
    next();
  });

  // Static files (optional)
  app.use(express.static(path.join(__dirname, 'public')));

  // Database configuration builders
  const dbConfigBuilders = {
    postgres: (env) =>
      env.POSTGRES_URL
        ? {
            host: 'localhost',
            port: env.POSTGRES_PORT || 5432,
            user: env.POSTGRES_USER || 'postgres',
            password: env.POSTGRES_PASSWORD || '',
            database: env.POSTGRES_DB || 'postgres',
          }
        : null,

    mysql: (env) =>
      env.MYSQL_URL
        ? {
            host: 'localhost',
            port: env.MYSQL_PORT || 3306,
            user: env.MYSQL_USER || 'root',
            password: env.MYSQL_PASSWORD || '',
            database: env.MYSQL_DB || 'mysql',
          }
        : null,

    sqlite: (env) => (env.SQLITE_DB ? { path: env.SQLITE_DB } : null),

    mongodb: (env) =>
      env.MONGODB_URL
        ? {
            url: env.MONGODB_URL,
            database: env.MONGODB_DB || 'test',
          }
        : null,
  };

  // Build configurations
  const configs = Object.entries(dbConfigBuilders).reduce((acc, [db, builder]) => {
    acc[db] = builder(envVars);
    return acc;
  }, {});

  // Base adapter
  class DatabaseAdapter {
    constructor(type, config) {
      this.type = type;
      this.config = config;
    }
    async testConnection() {
      throw new Error('Not implemented');
    }
    async getTables() {
      throw new Error('Not implemented');
    }
    async getData(_table, _limit) {
      throw new Error('Not implemented');
    }
    formatTableResult(rows, columnName = 'table_name') {
      return rows.map((row) => ({
        table_name: typeof row === 'object' ? row[columnName] || Object.values(row)[0] : row,
      }));
    }
  }

  class SQLAdapter extends DatabaseAdapter {
    async execute(_query) {
      throw new Error('Not implemented');
    }
    async testConnection() {
      await this.execute('SELECT 1');
    }
    getTableQuery() {
      throw new Error('Not implemented');
    }
    getDataQuery(_table, _limit) {
      throw new Error('Not implemented');
    }
    async getTables() {
      const rows = await this.execute(this.getTableQuery());
      return this.formatTableResult(rows);
    }
    async getData(table, limit) {
      return await this.execute(this.getDataQuery(table, limit));
    }
  }

  class PostgresAdapter extends SQLAdapter {
    async execute(query) {
      if (!Pool) {
        throw new Error('pg module is not installed. Run "npm ci" to install dependencies.');
      }
      const pool = new Pool(this.config);
      try {
        const result = await pool.query(query);
        return result.rows;
      } finally {
        await pool.end();
      }
    }
    getTableQuery() {
      return "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'";
    }
    getDataQuery(table, limit) {
      return `SELECT * FROM "${table}" LIMIT ${limit}`;
    }
  }

  class MySQLAdapter extends SQLAdapter {
    async execute(query) {
      if (!mysql) {
        throw new Error('mysql2 module is not installed. Run "npm ci" to install dependencies.');
      }
      const connection = await mysql.createConnection(this.config);
      try {
        const [rows] = await connection.execute(query);
        return rows;
      } finally {
        await connection.end();
      }
    }
    getTableQuery() {
      return 'SHOW TABLES';
    }
    getDataQuery(table, limit) {
      return `SELECT * FROM \`${table}\` LIMIT ${limit}`;
    }
  }

  class SQLiteAdapter extends SQLAdapter {
    execute(query) {
      if (!sqlite3) {
        throw new Error('sqlite3 module is not installed. Run "npm ci" to install dependencies.');
      }
      return new Promise((resolve, reject) => {
        const db = new sqlite3.Database(this.config.path);
        db.all(query, (err, rows) => {
          if (err) reject(err);
          else resolve(rows);
          db.close();
        });
      });
    }
    async testConnection() {
      if (!this.config || !this.config.path) {
        throw new Error('SQLite path not configured');
      }
      if (!fs.existsSync(this.config.path)) {
        throw new Error('SQLite database file not found');
      }
    }
    getTableQuery() {
      return "SELECT name as table_name FROM sqlite_master WHERE type='table'";
    }
    getDataQuery(table, limit) {
      return `SELECT * FROM "${table}" LIMIT ${limit}`;
    }
  }

  class MongoDBAdapter extends DatabaseAdapter {
    async withClient(callback) {
      if (!MongoClient) {
        throw new Error('mongodb module is not installed. Run "npm ci" to install dependencies.');
      }
      const client = new MongoClient(this.config.url);
      try {
        await client.connect();
        const db = client.db(this.config.database);
        return await callback(db);
      } finally {
        await client.close();
      }
    }
    async testConnection() {
      await this.withClient(async () => {});
    }
    async getTables() {
      return await this.withClient(async (db) => {
        const collections = await db.listCollections().toArray();
        return this.formatTableResult(collections, 'name');
      });
    }
    async getData(table, limit) {
      return await this.withClient(async (db) => {
        return await db.collection(table).find({}).limit(limit).toArray();
      });
    }
  }

  const adapterClasses = {
    postgres: PostgresAdapter,
    mysql: MySQLAdapter,
    sqlite: SQLiteAdapter,
    mongodb: MongoDBAdapter,
  };

  const adapters = Object.entries(configs).reduce((acc, [db, config]) => {
    acc[db] = config ? new adapterClasses[db](db, config) : null;
    return acc;
  }, {});

  async function testConnections() {
    const available = [];
    for (const [name, adapter] of Object.entries(adapters)) {
      if (!adapter) {
        console.log(`- ${name}: not configured`);
        continue;
      }
      try {
        console.log(`Testing ${name} connection...`);
        await adapter.testConnection();
        available.push(name);
        console.log(`✓ ${name} connection successful`);
      } catch (error) {
        console.log(`✗ ${name} connection failed: ${error.message}`);
        if (name === 'mysql' && adapter.config) {
          console.log(`  MySQL config: ${JSON.stringify(adapter.config, null, 2)}`);
        }
      }
    }
    return available;
  }

  async function handleApiRequest(req, res, operation) {
    try {
      const adapter = adapters[req.params.db];
      if (!adapter) {
        throw new Error(`${req.params.db} not configured`);
      }
      const result = await operation(adapter);
      res.json(result);
    } catch (error) {
      res.status(500).json({ error: error.message });
    }
  }

  // Routes
  app.get('/api/databases', async (_req, res) => {
    const available = await testConnections();
    res.json(available);
  });

  app.get('/api/:db/tables', (req, res) =>
    handleApiRequest(req, res, (adapter) => adapter.getTables()),
  );

  app.get('/api/:db/tables/:table/data', (req, res) =>
    handleApiRequest(req, res, (adapter) => {
      const limit = parseInt(req.query.limit, 10) || 50;
      return adapter.getData(req.params.table, limit);
    }),
  );

  app.get('/', (_req, res) => {
    // If UI file exists, serve it; else provide JSON message
    const file = path.join(__dirname, 'public', 'index.html');
    if (fs.existsSync(file)) {
      res.sendFile(file);
    } else {
      res.json({
        status: 'ok',
        mode: 'full',
        message:
          'Database viewer API is running. No UI assets found; use API endpoints or add public/index.html.',
        endpoints: ['/api/databases', '/api/:db/tables', '/api/:db/tables/:table/data'],
      });
    }
  });

  const server = app.listen(PORT, HOST, () => {
    console.log(`Database viewer running on http://${HOST}:${PORT}`);
    console.log('\nEnvironment variables expected:');
    const envInfo = {
      PostgreSQL: 'POSTGRES_URL, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_PORT',
      MySQL: 'MYSQL_URL, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DB, MYSQL_PORT',
      SQLite: 'SQLITE_DB',
      MongoDB: 'MONGODB_URL, MONGODB_DB',
    };
    Object.entries(envInfo).forEach(([db, vars]) => {
      console.log(`${db}: ${vars}`);
    });
  });

  return server;
}

// Entrypoint
if (ENABLE_FULL) {
  const srv = startExpressApp(PORT, HOST, mergedEnv);
  if (!srv) {
    // Express not present; keep process alive with a lite server to avoid startup failures
    createLiteServer(PORT, HOST);
  }
} else {
  // By default, run only a minimal http server that does not depend on external modules
  createLiteServer(PORT, HOST);
}
